version: "3.9"  # optional since v1.27.0
services:
  django:
    build: .
    command: sh -c "/etc/init.d/cups start && gunicorn --bind 0.0.0.0:8000 expressprinting.conf.wsgi"
    volumes:
      - .:/opt/expressprinting.conf
      - static_data:/opt/expressprinting.conf/templates/static
      - media_data:/opt/expressprinting.conf/templates/media
    expose:
      - 8000
      - 631
    environment:
      - DATABASE_URL=postgresql://admin:admin@db:5432/expressprinting_db
      - DEBUG=1
    depends_on:
      - db
  db:
    image: postgres
    volumes:
      - pg_data:/var/lib/postgresql/data/
    expose:
      - 5432
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin
      - POSTGRES_DB=expressprinting_db
  nginx:
    image: nginx
    depends_on:
      - django
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx-conf.d:/etc/nginx/conf.d
      - static_data:/var/www/html/static
      - media_data:/var/www/html/media
  certbot:
    image: certbot/certbot
volumes:
  pg_data:
  static_data:
  media_data: